package mx.uach.examen2parcial;
// Generated Nov 10, 2016 8:13:39 PM by Hibernate Tools 4.3.1



/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private int idalumnos;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String edad;
     private String curp;
     private String rfc;

    public Alumnos() {
    }

	
    public Alumnos(int idalumnos) {
        this.idalumnos = idalumnos;
    }
    public Alumnos(int idalumnos, String nombre, String apellido1, String apellido2, String edad, String curp, String rfc) {
       this.idalumnos = idalumnos;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.edad = edad;
       this.curp = curp;
       this.rfc = rfc;
    }
   
    public int getIdalumnos() {
        return this.idalumnos;
    }
    
    public void setIdalumnos(int idalumnos) {
        this.idalumnos = idalumnos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }




}


