package mx.uach.examen2parcial;
// Generated Nov 10, 2016 8:13:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comptadoras generated by hbm2java
 */
public class Comptadoras  implements java.io.Serializable {


     private int idComptadoras;
     private String modelo;
     private String tipo;
     private Date anoFab;
     private String vigente;

    public Comptadoras() {
    }

	
    public Comptadoras(int idComptadoras) {
        this.idComptadoras = idComptadoras;
    }
    public Comptadoras(int idComptadoras, String modelo, String tipo, Date anoFab, String vigente) {
       this.idComptadoras = idComptadoras;
       this.modelo = modelo;
       this.tipo = tipo;
       this.anoFab = anoFab;
       this.vigente = vigente;
    }
   
    public int getIdComptadoras() {
        return this.idComptadoras;
    }
    
    public void setIdComptadoras(int idComptadoras) {
        this.idComptadoras = idComptadoras;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getAnoFab() {
        return this.anoFab;
    }
    
    public void setAnoFab(Date anoFab) {
        this.anoFab = anoFab;
    }
    public String getVigente() {
        return this.vigente;
    }
    
    public void setVigente(String vigente) {
        this.vigente = vigente;
    }




}


