package mx.uach.examen2parcial;
// Generated Nov 10, 2016 8:13:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pelicula generated by hbm2java
 */
public class Pelicula  implements java.io.Serializable {


     private int idPelicula;
     private String titulo;
     private Date ano;
     private String sinapsis;
     private String vigente;

    public Pelicula() {
    }

	
    public Pelicula(int idPelicula) {
        this.idPelicula = idPelicula;
    }
    public Pelicula(int idPelicula, String titulo, Date ano, String sinapsis, String vigente) {
       this.idPelicula = idPelicula;
       this.titulo = titulo;
       this.ano = ano;
       this.sinapsis = sinapsis;
       this.vigente = vigente;
    }
   
    public int getIdPelicula() {
        return this.idPelicula;
    }
    
    public void setIdPelicula(int idPelicula) {
        this.idPelicula = idPelicula;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Date getAno() {
        return this.ano;
    }
    
    public void setAno(Date ano) {
        this.ano = ano;
    }
    public String getSinapsis() {
        return this.sinapsis;
    }
    
    public void setSinapsis(String sinapsis) {
        this.sinapsis = sinapsis;
    }
    public String getVigente() {
        return this.vigente;
    }
    
    public void setVigente(String vigente) {
        this.vigente = vigente;
    }




}


